---
f5-cis:
  bigip_login_secret: f5-bigip-ctlr-login
  rbac:
    create: true
  serviceAccount:
    create: true
    name: bigip-login
  namespace: f5-cis
  args:
    bigip_url: 10.2.1.89
    bigip_partition: f5-bigip-k8s-ctlr
    pool_member_type: nodeport
    manage-configmaps: true
    hubmode: true
  image:
    user: f5networks
    repo: k8s-bigip-ctlr
    pullPolicy: Always